#ifndef MIXER_REG_STR_TABLE_H
#define MIXER_REG_STR_TABLE_H


// pyFEdit generated file - DO NOT EDIT


#include "MIXERVars.h"

const registerNameMIXER_STR_TABLE[]
{
"NULL",
"PWIN_AILERON_LEFT",
"PWIN_ELEVATOR",
"PWIN_THROTTLE",
"PWIN_RUDDER",
"PWIN_AILERON_RIGHT",
"PWIN_FLAP_LEFT",
"PWIN_FLAP_RIGHT",
"TRIM_AILERON_LEFT",
"TRIM_ELEVATOR",
"TRIM_THROTTLE",
"TRIM_RUDDER",
"TRIM_AILERON_RIGHT",
"TRIM_FLAP_LEFT",
"TRIM_FLAP_RIGHT",
"APCON_ROLL",
"APCON_PITCH",
"APCON_THROTTLE",
"APCON_YAW",
"APCON_CAMBER",
"APCON_BRAKE",
"APCON_WAGGLE",
"APMODE_FULL",
"RADIO_MANUAL_MODE",
"APMODE_RADIO_ON",
"GAIN_MAN_MIX",
"MAN_GAIN_ROLL",
"MAN_GAIN_PITCH",
"MAN_GAIN_YAW",
"MAN_GAIN_THROTTLE",
"CON_ROLL",
"CON_PITCH",
"CON_YAW",
"CON_THROTTLE",
"CON_CAMBER",
"CON_BRAKE",
"CON_FLAP",
"PWOUT_AILERON_LEFT",
"PWOUT_ELEVATOR",
"PWOUT_THROTTLE",
"PWOUT_RUDDER",
"PWOUT_AILERON_RIGHT",
"PWOUT_FLAP_LEFT",
"PWOUT_FLAP_RIGHT",
"NULL_4",
"NULL_5",
"PWOUT_",
" "

};

#endif
