#ifndef MIXER_REGISTERS_H
#define MIXER_REGISTERS_H


// pyFEdit generated file - DO NOT EDIT


typedef enum
{
REG_MIXER_NULL,
REG_MIXER_PWIN_AILERON_LEFT,
REG_MIXER_PWIN_ELEVATOR,
REG_MIXER_PWIN_THROTTLE,
REG_MIXER_PWIN_RUDDER,
REG_MIXER_PWIN_AILERON_RIGHT,
REG_MIXER_PWIN_FLAP_LEFT,
REG_MIXER_PWIN_FLAP_RIGHT,
REG_MIXER_AP_CON_ROLL,
REG_MIXER_AP_CON_PITCH,
REG_MIXER_AP_CON_THROTTLE,
REG_MIXER_AP_CON_YAW,
REG_MIXER_AP_CON_CAMBER,
REG_MIXER_AP_CON_BRAKE,
REG_MIXER_MAN_GAIN_ROLL,
REG_MIXER_MAN_GAIN_PITCH,
REG_MIXER_MAN_GAIN_YAW,
REG_MIXER_MAN_GAIN_THROTTLE,
REG_MIXER_CON_ROLL,
REG_MIXER_CON_PITCH,
REG_MIXER_CON_YAW,
REG_MIXER_CON_THROTTLE,
REG_MIXER_CON_CAMBER,
REG_MIXER_CON_BRAKE,
REG_MIXER_CON_FLAP,
REG_MIXER_PWOUT_AILERON_LEFT,
REG_MIXER_PWOUT_ELEVATOR,
REG_MIXER_PWOUT_THROTTLE,
REG_MIXER_PWOUT_RUDDER,
REG_MIXER_PWOUT_AILERON_RIGHT,
REG_MIXER_PWOUT_FLAP_LEFT,
REG_MIXER_PWOUT_FLAP_RIGHT,
REG_MIXER_NULL_4,
REG_MIXER_NULL_5,
REG_MIXER_PWOUT_,
REG_MIXER_MAX
};

#endif
