#ifndef MIXER_REGISTERS_H
#define MIXER_REGISTERS_H


// pyFEdit generated file - DO NOT EDIT


typedef enum
{
REG_MIXER_NULL,
REG_MIXER_PWIN_AILERON_LEFT,
REG_MIXER_PWIN_ELEVATOR,
REG_MIXER_PWIN_THROTTLE,
REG_MIXER_PWIN_RUDDER,
REG_MIXER_PWIN_AILERON_RIGHT,
REG_MIXER_PWIN_FLAP_LEFT,
REG_MIXER_PWIN_FLAP_RIGHT,
REG_MIXER_TRIM_AILERON_LEFT,
REG_MIXER_TRIM_ELEVATOR,
REG_MIXER_TRIM_THROTTLE,
REG_MIXER_TRIM_RUDDER,
REG_MIXER_TRIM_AILERON_RIGHT,
REG_MIXER_TRIM_FLAP_LEFT,
REG_MIXER_TRIM_FLAP_RIGHT,
REG_MIXER_APCON_ROLL,
REG_MIXER_APCON_PITCH,
REG_MIXER_APCON_THROTTLE,
REG_MIXER_APCON_YAW,
REG_MIXER_APCON_CAMBER,
REG_MIXER_APCON_BRAKE,
REG_MIXER_APCON_WAGGLE,
REG_MIXER_APMODE_FULL,
REG_MIXER_RADIO_MANUAL_MODE,
REG_MIXER_APMODE_RADIO_ON,
REG_MIXER_GAIN_MAN_MIX,
REG_MIXER_MAN_GAIN_ROLL,
REG_MIXER_MAN_GAIN_PITCH,
REG_MIXER_MAN_GAIN_YAW,
REG_MIXER_MAN_GAIN_THROTTLE,
REG_MIXER_CON_ROLL,
REG_MIXER_CON_PITCH,
REG_MIXER_CON_YAW,
REG_MIXER_CON_THROTTLE,
REG_MIXER_CON_CAMBER,
REG_MIXER_CON_BRAKE,
REG_MIXER_CON_FLAP,
REG_MIXER_PWOUT_AILERON_LEFT,
REG_MIXER_PWOUT_ELEVATOR,
REG_MIXER_PWOUT_THROTTLE,
REG_MIXER_PWOUT_RUDDER,
REG_MIXER_PWOUT_AILERON_RIGHT,
REG_MIXER_PWOUT_FLAP_LEFT,
REG_MIXER_PWOUT_FLAP_RIGHT,
REG_MIXER_NULL_4,
REG_MIXER_NULL_5,
REG_MIXER_PWOUT_,
REG_MIXER_MAX
};

#endif
