#ifndef FLEXIFUNCTION_REGISTERS_H
#define FLEXIFUNCTION_REGISTERS_H
// pyFEdit generated file - DO NOT EDIT


typedef enum
{
REG_NULL,
REG_PWIN_ROLL,
REG_PWIN_PITCH,
REG_PWIN_THROTTLE,
REG_PWIN_YAW,
REG_PWIN_FLAP,
REG_PWIN_CAMBER,
REG_PWIN_BRAKE,
REG_TRIM_POINT,
REG_TRIM_THROTTLE,
REG_APCON_ROLL,
REG_APCON_PITCH,
REG_APCON_THROTTLE,
REG_APCON_YAW,
REG_APCON_CAMBER,
REG_APCON_BRAKE,
REG_APCON_WAGGLE,
REG_APMODE_FULL,
REG_RADIO_MANUAL_MODE,
REG_APMODE_RADIO_ON,
REG_GAIN_MAN_MIX,
REG_MAN_GAIN_ROLL,
REG_MAN_GAIN_PITCH,
REG_MAN_GAIN_YAW,
REG_MAN_GAIN_THROTTLE,
REG_CON_ROLL,
REG_CON_PITCH,
REG_CON_YAW,
REG_CON_THROTTLE,
REG_CON_CAMBER,
REG_CON_BRAKE,
REG_CON_FLAP,
REG_AILERON_L,
REG_ELEVATOR,
REG_THROTTLE,
REG_RUDDER,
REG_AILERON_R,
REG_FLAP_L,
REG_FLAP_R,
REG_MAX
};

#endif
