#ifndef MIXER_REG_STR_TABLE_H
#define MIXER_REG_STR_TABLE_H


// pyFEdit generated file - DO NOT EDIT


#include "MIXERVars.h"

const registerNameMIXER_STR_TABLE[]
{
"NULL",
"PWIN_ROLL",
"PWIN_PITCH",
"PWIN_THROTTLE",
"PWIN_YAW",
"PWIN_FLAP",
"PWIN_CAMBER",
"PWIN_BRAKE",
"TRIM_POINT",
"TRIM_THROTTLE",
"APCON_ROLL",
"APCON_PITCH",
"APCON_THROTTLE",
"APCON_YAW",
"APCON_CAMBER",
"APCON_BRAKE",
"APCON_WAGGLE",
"APMODE_FULL",
"RADIO_MANUAL_MODE",
"APMODE_RADIO_ON",
"GAIN_MAN_MIX",
"MAN_GAIN_ROLL",
"MAN_GAIN_PITCH",
"MAN_GAIN_YAW",
"MAN_GAIN_THROTTLE",
"CON_ROLL",
"CON_PITCH",
"CON_YAW",
"CON_THROTTLE",
"CON_CAMBER",
"CON_BRAKE",
"CON_FLAP",
"AILERON_L",
"ELEVATOR",
"THROTTLE",
"RUDDER",
"AILERON_R",
"FLAPMID_L",
"FLAPMID_R",
"FLAP_L",
"FLAP_R",
"SPOILER",
" "

};

#endif
