#ifndef MIXER_REGISTERS_H
#define MIXER_REGISTERS_H


// pyFEdit generated file - DO NOT EDIT


typedef enum
{
REG_MIXER_NULL,
REG_MIXER_PWIN_ROLL,
REG_MIXER_PWIN_PITCH,
REG_MIXER_PWIN_THROTTLE,
REG_MIXER_PWIN_YAW,
REG_MIXER_PWIN_FLAP,
REG_MIXER_PWIN_CAMBER,
REG_MIXER_PWIN_BRAKE,
REG_MIXER_TRIM_POINT,
REG_MIXER_TRIM_THROTTLE,
REG_MIXER_APCON_ROLL,
REG_MIXER_APCON_PITCH,
REG_MIXER_APCON_THROTTLE,
REG_MIXER_APCON_YAW,
REG_MIXER_APCON_CAMBER,
REG_MIXER_APCON_BRAKE,
REG_MIXER_APCON_WAGGLE,
REG_MIXER_APMODE_FULL,
REG_MIXER_RADIO_MANUAL_MODE,
REG_MIXER_APMODE_RADIO_ON,
REG_MIXER_GAIN_MAN_MIX,
REG_MIXER_MAN_GAIN_ROLL,
REG_MIXER_MAN_GAIN_PITCH,
REG_MIXER_MAN_GAIN_YAW,
REG_MIXER_MAN_GAIN_THROTTLE,
REG_MIXER_CON_ROLL,
REG_MIXER_CON_PITCH,
REG_MIXER_CON_YAW,
REG_MIXER_CON_THROTTLE,
REG_MIXER_CON_CAMBER,
REG_MIXER_CON_BRAKE,
REG_MIXER_CON_FLAP,
REG_MIXER_AILERON_L,
REG_MIXER_ELEVATOR,
REG_MIXER_THROTTLE,
REG_MIXER_RUDDER,
REG_MIXER_AILERON_R,
REG_MIXER_FLAPMID_L,
REG_MIXER_FLAPMID_R,
REG_MIXER_FLAP_L,
REG_MIXER_FLAP_R,
REG_MIXER_SPOILER,
REG_MIXER_MAX
};

#endif
